name: "My Podcasts"
slug: "my_podcasts"
description: "Simple Home Assistant Podcast Management Supplement"
version: "1.0"
startup: "application"
boot: "auto"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - media:rw

hassio_api: true
hassio_role: "default"
homeassistant_api: true
auth_api: true

# Settings for sidebar display
ingress: true
ingress_stream: true
ingress_port: 8099
panel_icon: "mdi:podcast"
panel_title: "My Podcasts"
panel_admin: false

# User access
auth_api: true
auth_role: "default"
advanced: false

# Options and schema
options:
  log_level: info
  update_interval: 60
  db_file: "/data/mypodcasts.db"
  safe_mode: false

schema:
  log_level: list(debug|info|warning|error)
  update_interval: int
  db_file: str
  safe_mode: bool